Add  the model, repository, service and controller for entity Information
christophperrins/poller-vertx-rxjava pull request #9
Opened 2020-09-14 10:41 UTC by melsner11

Adds the model, repository, service and controller for "Information".

Fixes #5

2020-09-14 12:02 UTC, christophperrins requested changes
Overall it makes sense to me.

- [ ] We need to talk to Damon or between ourselves whether the repository layer should be returning Entity POJO's or ResultSets/JsonObject

- [ ] POST and PUT's should return the Entity not the Id

- [ ] I didn't see any changes to the Application class. We need to deploy it in that class for it to function

2020-09-14 12:02 UTC, christophperrins commented on src/main/java/digital/vix/vertxdemo/controller/InformationController.java
> +	}
This doesn't need to be an rxStart because the information we get back is instantly ignored and not really used anywhere... 

```suggestion
	@Override
	public void start() {
		router.get("/api/information").handler(this::get);
		router.post("/api/information").handler(BodyHandler.create()).handler(this::add);
		router.put("/api/information").handler(BodyHandler.create()).handler(this::update);
		router.delete("/api/information/:id").handler(this::delete);
	}
```

2020-09-14 12:02 UTC, christophperrins commented on src/main/java/digital/vix/vertxdemo/controller/InformationController.java
> +	}
From what Damon said, we shouldn't be returning ids in a post, but rather the entity itself

2020-09-14 12:02 UTC, christophperrins commented on src/main/java/digital/vix/vertxdemo/controller/InformationController.java
> +	}
If POSTs are meant to return the Entity I presume the PUTs should return the entity also

2020-09-14 12:02 UTC, christophperrins commented on src/main/java/digital/vix/vertxdemo/repository/EndpointRepositoryImpl.java
> +		}
I recommend using StringBuilder

2020-09-14 12:02 UTC, christophperrins commented on src/main/java/digital/vix/vertxdemo/repository/EndpointRepositoryImpl.java
> +				.rxQueryWithParams("SELECT * FROM endpoints where id IN (" + queryExtension+ ")= ?", idsPara)
Might aid readability if you started the SQL string at the top, and sequentially built then feed the full item into the sqlClient  

I'm a bit confused why the final string looking like:
"SELECT * FROM endpoints where id IN (?, ?, ?, ?)= ?"

I think you don't need the last few characters?
```suggestion
				.rxQueryWithParams("SELECT * FROM endpoints where id IN (" + queryExtension+ ")", idsPara)
```

2020-09-14 12:02 UTC, christophperrins commented on src/main/java/digital/vix/vertxdemo/repository/InformationRepository.java
> +    public Single<Long> create(Information information);
We will have to ask Damon how livi organises their code. 

If its an InformationRepository should it be returning ResultSets or Information Objects... Might be worth having a chat about this

2020-09-14 12:02 UTC, christophperrins commented on src/main/java/digital/vix/vertxdemo/repository/InformationRepositoryImpl.java
> +                .rxQueryWithParams("SELECT * FROM information where endpoint_id IN (" + queryExtension+ ")= ?", idsPara)
does it need the = ? at the end?
```suggestion
                .rxQueryWithParams("SELECT * FROM information where endpoint_id IN (" + queryExtension+ ")", idsPara)
```

2020-09-14 12:02 UTC, christophperrins commented on src/main/java/digital/vix/vertxdemo/repository/InformationRepositoryImpl.java
> +
Might be worth returning the entity not the id

2020-09-15 13:30 UTC, melsner11 commented on src/main/java/digital/vix/vertxdemo/repository/InformationRepository.java
> +    public Single<Long> create(Information information);
Yes I agree. Definitely needs clarification.

2020-09-15 16:01 UTC, christophperrins commented on src/main/java/digital/vix/vertxdemo/controller/InformationController.java
> +			System.out.println(information);
Remove System out printouts please - can clog logs (or if its meant to be printed use logs)

2020-09-15 16:01 UTC, christophperrins commented on src/main/java/digital/vix/vertxdemo/controller/InformationController.java
> +	}
Information doesn't need to be returned here I don't think. It isn't used anywhere

2020-09-15 16:01 UTC, christophperrins commented on src/main/java/digital/vix/vertxdemo/controller/InformationController.java
> +	}
Same as post. I dont think we need it to return anything. Maybe to the user but not in the method

2020-09-15 16:01 UTC, christophperrins approved these changes

2020-09-15 16:03 UTC, merged